Repository Hahhhayam/TA-labs-1, pull requests merged in 2023-03, with the labels that each got.

#2 KP_2-print-graph-aproovement
  graph.jpg
  graph.png
Labels: documentation

#5 KP_2-print
  algorithm.js
  graph.png
  print.html
Labels: code, output

#7 KP_2-print
  algorithm.js
  graph.png
  print.html
Labels: code, output

#8 bug/crash-in-non-validate-value
  algorithm.js
Labels: bug
